services:
  rethinkdb:
    image: rethinkdb:2.3
    ports:
      - "8081:8080"
      - "28016:28015"
  postgres:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
