#!/bin/bash

docker-compose build --build-arg PYTHON_VERSION="$(cat .python-version)"
docker-compose run -w /code de-challenge python -m pytest tests/test.py -vv -p no:warnings --cov=lib --cov-report html
docker-compose down -v