#!/bin/bash

if [ ! -d ~/.pyenv ]
then
  curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
fi

pyenv install -s < .python-version
pyenv local < .python-version

if [ ! -d .venv ]
then
	echo "Creating python virtual environment"
    python -m venv .venv
fi

source .venv/bin/activate
pip install -r requirements.txt